### ISSUE TITLE
Installation not possible on Windows 2012 Server

### ISSUE THREAD

**Issue by marbetschar** [CopperEgg/copperegg-powershell#1]
If I follow the installation instructions (https://github.com/CopperEgg/copperegg-powershell) on a Windows 2012 Server, I receive the following error on importing the PowerYaml module. What I'm doing wrong here?

```
PS C:\Program Files (x86)\CopperEgg\Modules\CopperEgg> import-module ..\PowerYaml\PowerYaml.psm1
import-module : The specified module '..\PowerYaml\PowerYaml.psm1' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ import-module ..\PowerYaml\PowerYaml.psm1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (..\PowerYaml\PowerYaml.psm1:String) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by hurs4529** [comment]
Having this same problem on Server 2008 R2

**Comment by flutist599** [comment]
FileNotFoundException !!

you have probably not cloned the git-repositories before executing...

**Comment by gagan93jtg** [comment]
Hey @marbetschar , @hurs4529 , we have introduced new methods of monitoring for Windows systems now. Now you can monitor MSSQL / Azure SQL instances using an easy to use installation script which is available on your Uptime Cloud Monitor account. 

More details in this [this](http://community.idera.com/visualize-your-database-performance-from-the-cloud-amazon-sql-and-azure-sql/)  blog post
